//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group7_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLine
    {
        public int ID { get; set; }
        public Nullable<double> creditedAmount { get; set; }
        public Nullable<double> debitedAmount { get; set; }
        public string comment { get; set; }
        public int TransactionID { get; set; }
        public Nullable<int> MasterAccountID { get; set; }
        public Nullable<int> MasterAccountID2 { get; set; }
    
        public virtual MasterAccount MasterAccount1 { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual MasterAccount MasterAccount { get; set; }
    }
}
