//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group7_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TransactionLine
    {
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (MasterAccountID == MasterAccountID2)
            {
                yield return new ValidationResult(
                    "Credit and Debit accounts must be different.",
                    new[] { "MasterAccountID", "MasterAccountID2" }
                );
            }
        }

        public int ID { get; set; }
        public Nullable<double> creditedAmount { get; set; }
        public Nullable<double> debitedAmount { get; set; }
        public string comment { get; set; }
        public int TransactionID { get; set; }
        public int MasterAccountID { get; set; }
        public Nullable<int> MasterAccountID2 { get; set; }
    
        public virtual MasterAccount MasterAccount { get; set; }
        public virtual MasterAccount MasterAccount1 { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
