//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group7_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string userName { get; set; }
        public string encryptedPassword { get; set; }
        public Nullable<System.DateTime> passwordExpiryTime { get; set; }
        public Nullable<System.DateTime> userAccountExpiryDate { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual NonAdminUser NonAdminUser { get; set; }
    }
}
